# Создание ссылки
POST  http://localhost:3000/api/link/1984 HTTP/1.1
Content-Type: application/json

{
  "link": "http://localhost:3000/upload/b01a423d-0ac8-46d7-a50b-f005c4525080.jpg",
  "description": "Влад привет !!!"
}

###
# Получение детальной информации по ссылке
GET   http://localhost:3000/api/link/11 HTTP/1.1

###
## Редактирование ссылки
PATCH  http://localhost:3000/api/link/?idUser=1984&idLink=11 HTTP/1.1
Content-Type: application/json

{
  "tags": [
    "Опубликовано"
    ]
}

###
## Удаление ссылки
DELETE   http://localhost:3000/api/link/?idUser=1984&idLink=11 HTTP/1.1
