# Создание ссылки
POST  http://localhost:2000/api/link/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueUBtYWlsLmNvbSIsIm5hbWUiOiJUYW55IFNhem9ub3ZhIiwiaWF0IjoxNzM1NDk3MjA0LCJleHAiOjE3MzU0OTczMjR9.6vXHUGIsvX15eYaGK_wnYuwPiwskB5wESdUVzBSdRSM
Content-Type: application/json

{
  "link": "https://www.youtube.com/watch?v=cjNwrE5zHn8&t=2716s",
  "description": "Мая любимая фотография",
  "state": "Опубликовано"
}

###
# Получение детальной информации по ссылке
GET   http://localhost:2000/api/link/70 HTTP/1.1

###
## Редактирование ссылки
PATCH  http://localhost:2000/api/link/?idLink=41 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwODI3NjksImV4cCI6MTczNDA4Mjg4OX0.4jWoyuVkt65nMjiaUkcwSjVFHxHg0YXk07VwnTlQ7jg
Content-Type: application/json

{
  "tags": [
    "link",
    "Music",
    "music"
    ]
}

###
## Удаление ссылки
DELETE   http://localhost:2000/api/link/?idLink=71 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueSBTYXpvbm92YSIsIm5hbWUiOiJUYW55QG1haWwuY29tIiwiaWF0IjoxNzM1NDk3NDI5LCJleHAiOjE3MzU0OTc1NDl9.UZ9HIaH5ux_9PZNo0o58dYTKrnocusOUBlIb0Frv-4w
