# Создание ссылки
POST  http://localhost:3000/api/link/674ef86bbbe20f079fdb30bd HTTP/1.1
Content-Type: application/json

{
  "link": "https://www.youtube.com/watch?v=cjNwrE5zHn8&t=2716s",
  "description": "Мая любимая фотография"
}

###
# Получение детальной информации по ссылке
GET   http://localhost:3000/api/link/32 HTTP/1.1

###
## Редактирование ссылки
PATCH  http://localhost:3000/api/link/?idUser=674ef86bbbe20f079fdb30bd&idLink=33 HTTP/1.1
Content-Type: application/json

{
  "tags": [
    "link",
    "Music",
    "music"
    ]
}

###
## Удаление ссылки
DELETE   http://localhost:3000/api/link/?idUser=674ef86bbbe20f079fdb30bd&idLink=32 HTTP/1.1
