# Создание текст
POST  http://localhost:2000/api/text/?newsletter=true HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueSBTYXpvbm92YSIsIm5hbWUiOiJUYW55QG1haWwuY29tIiwiaWF0IjoxNzM1NDc0MjM0LCJleHAiOjE3MzU0NzQzNTR9.X6is0AljCFfVRGamdcioqlKiTgeVCtH2TJTwXVas5Lk
Content-Type: application/json

{
  "name": "В Дубаи. Поездка на две нидели.",
  "preview": "Как поездка в Дубай, обошлась не дорого но получил уйму впечетлений.",
  "text": "В четверг с группой вылители сомалетом вечером. Полет до Дубай был спокойный, уймо знакомств и общения.",
  "state": "Опубликовано"
}

###
# Получение детальной информации по тексту
GET   http://localhost:2000/api/text/55 HTTP/1.1

###
## Редактирование текст
PATCH  http://localhost:2000/api/text/?idText=65 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueSBTYXpvbm92YSIsIm5hbWUiOiJUYW55QG1haWwuY29tIiwiaWF0IjoxNzM1NDc1MDcxLCJleHAiOjE3MzU0NzUxOTF9.ufzRiAwe3ORJbDZ4N5Xb3kF-X6htWoSgIytn0VRLXGE
Content-Type: application/json

{
  "tags": [
    "Vlad",
    "UnidentifiedRaccoon"
  ]
}

###
## Удаление текста
DELETE   http://localhost:2000/api/text/?idText=65 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueUBtYWlsLmNvbSIsIm5hbWUiOiJUYW55IFNhem9ub3ZhIiwiaWF0IjoxNzM1NDc1MTUzLCJleHAiOjE3MzU0NzUyNzN9.aGJtJFyYua8mC8ZS_u18bdABlpshX1g751VGBfWoFZY
