# Создание текст
POST  http://localhost:2000/api/text/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwNzM3NDksImV4cCI6MTczNDA3Mzg2OX0.X5s4suo5OCpF4yOYCh9cNGLhv39ckOJXo97yccANPHg
Content-Type: application/json

{
  "name": "В Дубаи. Поездка на две нидели.",
  "preview": "Как поездка в Дубай, обошлась не дорого но получил уйму впечетлений.",
  "text": "В четверг с группой вылители сомалетом вечером. Полет до Дубай был спокойный, уймо знакомств и общения."
}

###
# Получение детальной информации по тексту
GET   http://localhost:2000/api/text/36 HTTP/1.1

###
## Редактирование текст
PATCH  http://localhost:2000/api/text/?idText=36 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwNzM4NDUsImV4cCI6MTczNDA3Mzk2NX0.h-bzfBdvAvdfo_gaOfGeLilouQA9gI4O2zIqY5gV3-U
Content-Type: application/json

{
  "state": "Опубликовано"
}

###
## Удаление текста
DELETE   http://localhost:2000/api/text/?idText=36 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwNzM4NDUsImV4cCI6MTczNDA3Mzk2NX0.h-bzfBdvAvdfo_gaOfGeLilouQA9gI4O2zIqY5gV3-U
