# Создание текст
POST  http://localhost:3000/api/text/674ef86bbbe20f079fdb30bd HTTP/1.1
Content-Type: application/json

{
  "name": "В отпуске. Поездка в горы по туру выходного дня.",
  "preview": "Как поездка в горы Домбая, обошлась не дорого но получил уйму впечетлений.",
  "text": "В четверг с группой выехали поздно вечером. Поездка до Домбая была веселой, уймо знакомств и общения."
}

###
# Получение детальной информации по тексту
GET   http://localhost:3000/api/text/13 HTTP/1.1

###
## Редактирование текст
PATCH  http://localhost:3000/api/text/?idUser=674ef86bbbe20f079fdb30bd&idText=13 HTTP/1.1
Content-Type: application/json

{
  "state": "Опубликовано"
}

###
## Удаление текста
DELETE   http://localhost:3000/api/text/?idUser=674ef86bbbe20f079fdb30bd&idText=13 HTTP/1.1
