# Создание видео
POST  http://localhost:2000/api/video/?newsletter=true HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueUBtYWlsLmNvbSIsIm5hbWUiOiJUYW55IFNhem9ub3ZhIiwiaWF0IjoxNzM1MzA0NTM4LCJleHAiOjE3MzUzMDQ2NTh9.hIgxZetGWMfSCJbejYl1a9SzR9BU93aWpytR3vprBxs
Content-Type: application/json

{
  "name": "Это ссылка на видео с толантлевой девушкой.",
  "link": "https://www.youtube.com/watch?v=_MmOZKh0sSc",
  "state": "Опубликовано"
}

###
# Получение детальной информации по видео
GET   http://localhost:2000/api/video/64 HTTP/1.1

###
## Редактирование видео
PATCH  http://localhost:2000/api/video/?idVideo=63 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueSBTYXpvbm92YSIsIm5hbWUiOiJUYW55QG1haWwuY29tIiwiaWF0IjoxNzM1Mzg1NjUyLCJleHAiOjE3MzUzODU3NzJ9.feIRzRXtVxtZ20imGr2v4GDOayl7urkDRyFHJqRQaOE
Content-Type: application/json

{
  "tags": [
    "Vlad",
    "UnidentifiedRaccoon"
  ],
  "state": "Черновик"
}

###
## Удаление видео
DELETE   http://localhost:2000/api/video/?idVideo=63 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueUBtYWlsLmNvbSIsIm5hbWUiOiJUYW55IFNhem9ub3ZhIiwiaWF0IjoxNzM1Mzg2MDc4LCJleHAiOjE3MzUzODYxOTh9.NRbxdAXnwIZlk-bApwHg1OBZe84S14mhsobE46D1F2Y
Content-Type: application/json
