# Создание видео
POST  http://localhost:3000/api/video/1984 HTTP/1.1
Content-Type: application/json

{
  "name": "Vlad",
  "link": "http://localhost:3000/upload/b01a423d-0ac8-46d7-a50b-f005c4525080.jpg",
  "tags": [
    "Vlad",
    "Alex"
  ]
}

###
# Получение детальной информации по видео
GET   http://localhost:3000/api/video/7 HTTP/1.1

###
## Редактирование видео
PATCH  http://localhost:3000/api/video/?idUser=1984&idVideo=2 HTTP/1.1
Content-Type: application/json

{
  "tags": [
    "Vlad"
  ]
}

###
## Удаление видео
DELETE   http://localhost:3000/api/video/?idUser=1984&idVideo=2 HTTP/1.1
