# Создание видео
POST  http://localhost:2000/api/video/?newsletter=true HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZCBTYXpvbm92IiwibmFtZSI6IlZsYWRAbWFpbC5jb20iLCJpYXQiOjE3MzQ3MDk1MjQsImV4cCI6MTczNDcwOTY0NH0.iWYFc74LRUq1EhBZ_YaALV3wrl-zwejC46PO8nVSp1Q
Content-Type: application/json

{
  "name": "Это ссылка на видео с толантлевой девушкой.",
  "link": "https://www.youtube.com/watch?v=_MmOZKh0sSc",
  "state": "Опубликовано"
}

###
# Получение детальной информации по видео
GET   http://localhost:3000/api/video/25 HTTP/1.1

###
## Редактирование видео
PATCH  http://localhost:2000/api/video/?idVideo=35 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwMTA2NDQsImV4cCI6MTczNDAxMDc2NH0.K5ipzT5Zv4Cj5xxZazUNuGD6n1SDyn7MaDlFfjfe2jo
Content-Type: application/json

{
  "tags": [
    "Vlad"
  ],
  "state": "Опубликовано"
}

###
## Удаление видео
DELETE   http://localhost:2000/api/video/?idVideo=37 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZCBTYXpvbm92IiwibmFtZSI6IlZsYWRAbWFpbC5jb20iLCJpYXQiOjE3MzQ1OTE2MzEsImV4cCI6MTczNDY3ODAzMX0.zEEsKOcDXQcmFsfD-9v97SqZhqC_Kf6WlhcTS9M-K9Q
