# Отправить изображение
POST http://localhost:6500/api/user/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="barbershop.png"
Content-Type: image/jpeg

< C:/Users/User/Desktop/readme/markup/img/barbershop.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# Creating a new user
POST  http://localhost:6500/api/user/registration HTTP/1.1
Content-Type: application/json

{
  "name": "Tany Sazonova",
  "email": "Tany@mail.com",
  "password": "23Tany",
  "avatar": "/upload/2024/12/910ac106-c939-4f74-b6ff-96d462fc8253.png"
}

###
# User authorization
GET   http://localhost:6500/api/user/authentication HTTP/1.1
Content-Type: application/json

{
  "email": "Tany@mail.com",
  "password": "23Tany"
}

###
## Сменить пароль пользователя
PATCH  http://localhost:6500/api/user/change?oldPassword=Volga_2025&newPassword=Vlad.V_1984 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQyNjM4MTYsImV4cCI6MTczNDI2MzkzNn0.iVV6QZiV3isWLX87IGxpr54uB5e1sJ6oFllHtRv8STg

###
## Запросить детальную информацию по определенному пользователю
GET http://localhost:6500/api/user/6763c3c4e58f2306b5a50a90 HTTP/1.1

###
## Получение новой пары  accessToken и refreshToken
POST  http://localhost:6500/api/user/tokens HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueUBtYWlsLmNvbSIsIm5hbWUiOiJUYW55IFNhem9ub3ZhIiwiaWF0IjoxNzM1NzQ4NjQ2LCJleHAiOjE3MzU4MzUwNDZ9.-2YkVZvTnMToNnIBA9FcupJat2LN9auX-hImygWOr3I
