# Создание Комментария
POST  http://localhost:2000/api/comment/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwODUxMzQsImV4cCI6MTczNDA4NTI1NH0.CRF3CMfpb9m2DiqW3Py1-vq7Efg9L0GUxocuz0_Etxc
Content-Type: application/json

{
  "text": "This is photo is cool !!!. Me like",
  "idPublication": 30
}

###
# Получение  списка комментариев
GET   http://localhost:2000/api/comment/30 HTTP/1.1

###
## Удаление комментария
DELETE   http://localhost:2000/api/comment/?idComment=2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwODUyNjIsImV4cCI6MTczNDA4NTM4Mn0.phhna01fNLLLRrXc0KORXtuVdK1SuIc7sJCFRp5G3K8
