# Создание Комментария
POST  http://localhost:2000/api/comment/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueUBtYWlsLmNvbSIsIm5hbWUiOiJUYW55IFNhem9ub3ZhIiwiaWF0IjoxNzM1NzQ4NjQ2LCJleHAiOjE3MzU3NDg3NjZ9.vc-KaHPdE65lTzvrRKJTftc1ndEm2y_btyUnhH2NP8g
Content-Type: application/json

{
  "text": "This is photo is cool !!!. Me like",
  "idPublication": 30
}

###
# Получение  списка комментариев
GET   http://localhost:2000/api/comment/16 HTTP/1.1

###
## Удаление комментария
DELETE   http://localhost:2000/api/comment/?idComment=5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueSBTYXpvbm92YSIsIm5hbWUiOiJUYW55QG1haWwuY29tIiwiaWF0IjoxNzM1NzQ4NzQxLCJleHAiOjE3MzU3NDg4NjF9.-rC_1wPFC6sjw9foyMsTw-8-g3m1zlSaPwqM6maHexU
