# Создание видео
POST  http://localhost:2000/api/repost/?idPublication=56 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmI5Y2Q1ZTVhMWY0ZmMyYTcxMDczNyIsImVtYWlsIjoiVGFueSBTYXpvbm92YSIsIm5hbWUiOiJUYW55QG1haWwuY29tIiwiaWF0IjoxNzM1NTY4NzIxLCJleHAiOjE3MzU1Njg4NDF9.-DRhoqZxKmjsc0w7mRz80nk-euRJ5H3cCz-vzKZky-U
