# Создание цитаты
POST  http://localhost:2000/api/quote/?newsletter=true HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZCBTYXpvbm92IiwibmFtZSI6IlZsYWRAbWFpbC5jb20iLCJpYXQiOjE3MzQ3NzU5NDIsImV4cCI6MTczNDc3NjA2Mn0.0l4cySqiP8GsxE21cL1gTbYBDR_CZEPmwAgxIGYBJgI
Content-Type: application/json

{
  "text": "Кто, имея знания, делает вид, что не знает, тот выше всех.",
  "name": "Igor",
  "state": "Опубликовано"
}

###
# Получение детальной информации по цитате
GET   http://localhost:3000/api/quote/15 HTTP/1.1

###
## Редактирование цитаты
PATCH  http://localhost:2000/api/quote/?idQuote=39 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwNzY2NzcsImV4cCI6MTczNDA3Njc5N30.t_5PsLQOq02RgEWm9WUTZRHttnGDziphxPrzSJGQGBw
Content-Type: application/json

{
  "tags": [
    "Quote",
    "Igor"
    ]
}

###
## Удаление цитаты
DELETE   http://localhost:2000/api/quote/?idQuote=39 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYxOGRhYzA5YjM5ZDRkYTdmODlkNSIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIFNhem9ub3YiLCJpYXQiOjE3MzQwNzY2NzcsImV4cCI6MTczNDA3Njc5N30.t_5PsLQOq02RgEWm9WUTZRHttnGDziphxPrzSJGQGBw
